//
// Created by user on 07.05.2025.
//

#ifdef STM32H523xx
#include "stm32h5xx.h"
#endif

#if defined(UART_APP_CONFIG)
#include UART_APP_CONFIG
#else
#error "please define UART_APP_CONFIG path"
#endif


extern UART_HandleTypeDef *getUartHalHandleByUSART(USART_TypeDef *usart);

extern DMA_HandleTypeDef *getDMAHalHandleByDMA(DMA_Channel_TypeDef *dma);

#ifdef UART1_HW

void USART1_IRQHandler(void) {
    HAL_UART_IRQHandler(getUartHalHandleByUSART(USART1));
}
#endif

#ifdef UART2_HW
void USART2_IRQHandler(void) {
    HAL_UART_IRQHandler(getUartHalHandleByUSART(USART2));
}
#endif

#ifdef UART3_HW
void USART3_IRQHandler(void)
{

    HAL_UART_IRQHandler(getUartHalHandleByUSART(USART3));
}
#endif

#ifdef UART4_HW
void UART4_IRQHandler(void)
{

    HAL_UART_IRQHandler(getUartHalHandleByUSART(USART3));
}
#endif

#ifdef UART5_HW

void UART5_IRQHandler(void) {
    HAL_UART_IRQHandler(getUartHalHandleByUSART(UART5));
}
#endif

#ifdef UART6_HW

void USART6_IRQHandler(void)
{
    HAL_UART_IRQHandler(getUartHalHandleByUSART(USART6));
}
#endif

#if  defined UART1_HW_DMA_RX_CHANNEL &&  UART1_HW_DMA_RX_CHANNEL  == GPDMA1_Channel0_BASE_NS || defined UART1_HW_DMA_TX_CHANNEL && UART1_HW_DMA_TX_CHANNEL == GPDMA1_Channel0_BASE_NS \
    || defined UART2_HW_DMA_RX_CHANNEL && UART2_HW_DMA_RX_CHANNEL == GPDMA1_Channel0_BASE_NS || defined UART2_HW_DMA_TX_CHANNEL && UART2_HW_DMA_TX_CHANNEL == GPDMA1_Channel0_BASE_NS \
    || defined UART3_HW_DMA_RX_CHANNEL && UART3_HW_DMA_RX_CHANNEL == GPDMA1_Channel0_BASE_NS || defined UART3_HW_DMA_TX_CHANNEL && UART3_HW_DMA_TX_CHANNEL == GPDMA1_Channel0_BASE_NS \
    || defined UART4_HW_DMA_RX_CHANNEL && UART4_HW_DMA_RX_CHANNEL == GPDMA1_Channel0_BASE_NS || defined UART4_HW_DMA_TX_CHANNEL && UART4_HW_DMA_TX_CHANNEL == GPDMA1_Channel0_BASE_NS \
    || defined UART5_HW_DMA_RX_CHANNEL && UART5_HW_DMA_RX_CHANNEL == GPDMA1_Channel0_BASE_NS || defined UART5_HW_DMA_TX_CHANNEL && UART5_HW_DMA_TX_CHANNEL == GPDMA1_Channel0_BASE_NS \
    || defined UART6_HW_DMA_RX_CHANNEL && UART6_HW_DMA_RX_CHANNEL == GPDMA1_Channel0_BASE_NS || defined UART6_HW_DMA_TX_CHANNEL && UART6_HW_DMA_TX_CHANNEL == GPDMA1_Channel0_BASE_NS
void GPDMA1_Channel0_IRQHandler(void) {
    HAL_DMA_IRQHandler(getDMAHalHandleByDMA(GPDMA1_Channel0));
}
#endif

#if  defined UART1_HW_DMA_RX_CHANNEL &&  UART1_HW_DMA_RX_CHANNEL  == GPDMA1_Channel1_BASE_NS || defined UART1_HW_DMA_TX_CHANNEL && UART1_HW_DMA_TX_CHANNEL == GPDMA1_Channel1_BASE_NS \
|| defined UART2_HW_DMA_RX_CHANNEL && UART2_HW_DMA_RX_CHANNEL == GPDMA1_Channel1_BASE_NS || defined UART2_HW_DMA_TX_CHANNEL && UART2_HW_DMA_TX_CHANNEL == GPDMA1_Channel1_BASE_NS \
|| defined UART3_HW_DMA_RX_CHANNEL && UART3_HW_DMA_RX_CHANNEL == GPDMA1_Channel1_BASE_NS || defined UART3_HW_DMA_TX_CHANNEL && UART3_HW_DMA_TX_CHANNEL == GPDMA1_Channel1_BASE_NS \
|| defined UART4_HW_DMA_RX_CHANNEL && UART4_HW_DMA_RX_CHANNEL == GPDMA1_Channel1_BASE_NS || defined UART4_HW_DMA_TX_CHANNEL && UART4_HW_DMA_TX_CHANNEL == GPDMA1_Channel1_BASE_NS \
|| defined UART5_HW_DMA_RX_CHANNEL && UART5_HW_DMA_RX_CHANNEL == GPDMA1_Channel1_BASE_NS || defined UART5_HW_DMA_TX_CHANNEL && UART5_HW_DMA_TX_CHANNEL == GPDMA1_Channel1_BASE_NS \
|| defined UART6_HW_DMA_RX_CHANNEL && UART6_HW_DMA_RX_CHANNEL == GPDMA1_Channel1_BASE_NS || defined UART6_HW_DMA_TX_CHANNEL && UART6_HW_DMA_TX_CHANNEL == GPDMA1_Channel1_BASE_NS
void GPDMA1_Channel1_IRQHandler(void) {
    HAL_DMA_IRQHandler(getDMAHalHandleByDMA(GPDMA1_Channel1));
}
#endif


#if  defined UART1_HW_DMA_RX_CHANNEL &&  UART1_HW_DMA_RX_CHANNEL  == GPDMA1_Channel2_BASE_NS || defined UART1_HW_DMA_TX_CHANNEL && UART1_HW_DMA_TX_CHANNEL == GPDMA1_Channel2_BASE_NS \
|| defined UART2_HW_DMA_RX_CHANNEL && UART2_HW_DMA_RX_CHANNEL == GPDMA1_Channel2_BASE_NS || defined UART2_HW_DMA_TX_CHANNEL && UART2_HW_DMA_TX_CHANNEL == GPDMA1_Channel2_BASE_NS \
|| defined UART3_HW_DMA_RX_CHANNEL && UART3_HW_DMA_RX_CHANNEL == GPDMA1_Channel2_BASE_NS || defined UART3_HW_DMA_TX_CHANNEL && UART3_HW_DMA_TX_CHANNEL == GPDMA1_Channel2_BASE_NS \
|| defined UART4_HW_DMA_RX_CHANNEL && UART4_HW_DMA_RX_CHANNEL == GPDMA1_Channel2_BASE_NS || defined UART4_HW_DMA_TX_CHANNEL && UART4_HW_DMA_TX_CHANNEL == GPDMA1_Channel2_BASE_NS \
|| defined UART5_HW_DMA_RX_CHANNEL && UART5_HW_DMA_RX_CHANNEL == GPDMA1_Channel2_BASE_NS || defined UART5_HW_DMA_TX_CHANNEL && UART5_HW_DMA_TX_CHANNEL == GPDMA1_Channel2_BASE_NS \
|| defined UART6_HW_DMA_RX_CHANNEL && UART6_HW_DMA_RX_CHANNEL == GPDMA1_Channel2_BASE_NS || defined UART6_HW_DMA_TX_CHANNEL && UART6_HW_DMA_TX_CHANNEL == GPDMA1_Channel2_BASE_NS
void GPDMA1_Channel2_IRQHandler(void) {
    HAL_DMA_IRQHandler(getDMAHalHandleByDMA(GPDMA1_Channel2));
}
#endif


#if  defined UART1_HW_DMA_RX_CHANNEL &&  UART1_HW_DMA_RX_CHANNEL  == GPDMA1_Channel3_BASE_NS || defined UART1_HW_DMA_TX_CHANNEL && UART1_HW_DMA_TX_CHANNEL == GPDMA1_Channel3_BASE_NS \
|| defined UART2_HW_DMA_RX_CHANNEL && UART2_HW_DMA_RX_CHANNEL == GPDMA1_Channel3_BASE_NS || defined UART2_HW_DMA_TX_CHANNEL && UART2_HW_DMA_TX_CHANNEL == GPDMA1_Channel3_BASE_NS \
|| defined UART3_HW_DMA_RX_CHANNEL && UART3_HW_DMA_RX_CHANNEL == GPDMA1_Channel3_BASE_NS || defined UART3_HW_DMA_TX_CHANNEL && UART3_HW_DMA_TX_CHANNEL == GPDMA1_Channel3_BASE_NS \
|| defined UART4_HW_DMA_RX_CHANNEL && UART4_HW_DMA_RX_CHANNEL == GPDMA1_Channel3_BASE_NS || defined UART4_HW_DMA_TX_CHANNEL && UART4_HW_DMA_TX_CHANNEL == GPDMA1_Channel3_BASE_NS \
|| defined UART5_HW_DMA_RX_CHANNEL && UART5_HW_DMA_RX_CHANNEL == GPDMA1_Channel3_BASE_NS || defined UART5_HW_DMA_TX_CHANNEL && UART5_HW_DMA_TX_CHANNEL == GPDMA1_Channel3_BASE_NS \
|| defined UART6_HW_DMA_RX_CHANNEL && UART6_HW_DMA_RX_CHANNEL == GPDMA1_Channel3_BASE_NS || defined UART6_HW_DMA_TX_CHANNEL && UART6_HW_DMA_TX_CHANNEL == GPDMA1_Channel3_BASE_NS
void GPDMA1_Channel3_IRQHandler(void) {
    HAL_DMA_IRQHandler(getDMAHalHandleByDMA(GPDMA1_Channel3));
}
#endif

#if  defined UART1_HW_DMA_RX_CHANNEL &&  UART1_HW_DMA_RX_CHANNEL  == GPDMA1_Channel4_BASE_NS || defined UART1_HW_DMA_TX_CHANNEL && UART1_HW_DMA_TX_CHANNEL == GPDMA1_Channel4_BASE_NS \
|| defined UART2_HW_DMA_RX_CHANNEL && UART2_HW_DMA_RX_CHANNEL == GPDMA1_Channel4_BASE_NS || defined UART2_HW_DMA_TX_CHANNEL && UART2_HW_DMA_TX_CHANNEL == GPDMA1_Channel4_BASE_NS \
|| defined UART3_HW_DMA_RX_CHANNEL && UART3_HW_DMA_RX_CHANNEL == GPDMA1_Channel4_BASE_NS || defined UART3_HW_DMA_TX_CHANNEL && UART3_HW_DMA_TX_CHANNEL == GPDMA1_Channel4_BASE_NS \
|| defined UART4_HW_DMA_RX_CHANNEL && UART4_HW_DMA_RX_CHANNEL == GPDMA1_Channel4_BASE_NS || defined UART4_HW_DMA_TX_CHANNEL && UART4_HW_DMA_TX_CHANNEL == GPDMA1_Channel4_BASE_NS \
|| defined UART5_HW_DMA_RX_CHANNEL && UART5_HW_DMA_RX_CHANNEL == GPDMA1_Channel4_BASE_NS || defined UART5_HW_DMA_TX_CHANNEL && UART5_HW_DMA_TX_CHANNEL == GPDMA1_Channel4_BASE_NS \
|| defined UART6_HW_DMA_RX_CHANNEL && UART6_HW_DMA_RX_CHANNEL == GPDMA1_Channel4_BASE_NS || defined UART6_HW_DMA_TX_CHANNEL && UART6_HW_DMA_TX_CHANNEL == GPDMA1_Channel4_BASE_NS
void GPDMA1_Channel4_IRQHandler(void) {
    HAL_DMA_IRQHandler(getDMAHalHandleByDMA(GPDMA1_Channel4));
}
#endif

#if  defined UART1_HW_DMA_RX_CHANNEL &&  UART1_HW_DMA_RX_CHANNEL  == GPDMA1_Channel5_BASE_NS || defined UART1_HW_DMA_TX_CHANNEL && UART1_HW_DMA_TX_CHANNEL == GPDMA1_Channel5_BASE_NS \
|| defined UART2_HW_DMA_RX_CHANNEL && UART2_HW_DMA_RX_CHANNEL == GPDMA1_Channel5_BASE_NS || defined UART2_HW_DMA_TX_CHANNEL && UART2_HW_DMA_TX_CHANNEL == GPDMA1_Channel5_BASE_NS \
|| defined UART3_HW_DMA_RX_CHANNEL && UART3_HW_DMA_RX_CHANNEL == GPDMA1_Channel5_BASE_NS || defined UART3_HW_DMA_TX_CHANNEL && UART3_HW_DMA_TX_CHANNEL == GPDMA1_Channel5_BASE_NS \
|| defined UART4_HW_DMA_RX_CHANNEL && UART4_HW_DMA_RX_CHANNEL == GPDMA1_Channel5_BASE_NS || defined UART4_HW_DMA_TX_CHANNEL && UART4_HW_DMA_TX_CHANNEL == GPDMA1_Channel5_BASE_NS \
|| defined UART5_HW_DMA_RX_CHANNEL && UART5_HW_DMA_RX_CHANNEL == GPDMA1_Channel5_BASE_NS || defined UART5_HW_DMA_TX_CHANNEL && UART5_HW_DMA_TX_CHANNEL == GPDMA1_Channel5_BASE_NS \
|| defined UART6_HW_DMA_RX_CHANNEL && UART6_HW_DMA_RX_CHANNEL == GPDMA1_Channel5_BASE_NS || defined UART6_HW_DMA_TX_CHANNEL && UART6_HW_DMA_TX_CHANNEL == GPDMA1_Channel5_BASE_NS
void GPDMA1_Channel5_IRQHandler(void) {
    HAL_DMA_IRQHandler(getDMAHalHandleByDMA(GPDMA1_Channel5));
}
#endif


#if  defined UART1_HW_DMA_RX_CHANNEL &&  UART1_HW_DMA_RX_CHANNEL  == GPDMA1_Channel6_BASE_NS || defined UART1_HW_DMA_TX_CHANNEL && UART1_HW_DMA_TX_CHANNEL == GPDMA1_Channel6_BASE_NS \
|| defined UART2_HW_DMA_RX_CHANNEL && UART2_HW_DMA_RX_CHANNEL == GPDMA1_Channel6_BASE_NS || defined UART2_HW_DMA_TX_CHANNEL && UART2_HW_DMA_TX_CHANNEL == GPDMA1_Channel6_BASE_NS \
|| defined UART3_HW_DMA_RX_CHANNEL && UART3_HW_DMA_RX_CHANNEL == GPDMA1_Channel6_BASE_NS || defined UART3_HW_DMA_TX_CHANNEL && UART3_HW_DMA_TX_CHANNEL == GPDMA1_Channel6_BASE_NS \
|| defined UART4_HW_DMA_RX_CHANNEL && UART4_HW_DMA_RX_CHANNEL == GPDMA1_Channel6_BASE_NS || defined UART4_HW_DMA_TX_CHANNEL && UART4_HW_DMA_TX_CHANNEL == GPDMA1_Channel6_BASE_NS \
|| defined UART5_HW_DMA_RX_CHANNEL && UART5_HW_DMA_RX_CHANNEL == GPDMA1_Channel6_BASE_NS || defined UART5_HW_DMA_TX_CHANNEL && UART5_HW_DMA_TX_CHANNEL == GPDMA1_Channel6_BASE_NS \
|| defined UART6_HW_DMA_RX_CHANNEL && UART6_HW_DMA_RX_CHANNEL == GPDMA1_Channel6_BASE_NS || defined UART6_HW_DMA_TX_CHANNEL && UART6_HW_DMA_TX_CHANNEL == GPDMA1_Channel6_BASE_NS
void GPDMA1_Channel6_IRQHandler(void) {
    HAL_DMA_IRQHandler(getDMAHalHandleByDMA(GPDMA1_Channel6));
}
#endif

#if  defined UART1_HW_DMA_RX_CHANNEL &&  UART1_HW_DMA_RX_CHANNEL  == GPDMA1_Channel7_BASE_NS || defined UART1_HW_DMA_TX_CHANNEL && UART1_HW_DMA_TX_CHANNEL == GPDMA1_Channel7_BASE_NS \
|| defined UART2_HW_DMA_RX_CHANNEL && UART2_HW_DMA_RX_CHANNEL == GPDMA1_Channel7_BASE_NS || defined UART2_HW_DMA_TX_CHANNEL && UART2_HW_DMA_TX_CHANNEL == GPDMA1_Channel7_BASE_NS \
|| defined UART3_HW_DMA_RX_CHANNEL && UART3_HW_DMA_RX_CHANNEL == GPDMA1_Channel7_BASE_NS || defined UART3_HW_DMA_TX_CHANNEL && UART3_HW_DMA_TX_CHANNEL == GPDMA1_Channel7_BASE_NS \
|| defined UART4_HW_DMA_RX_CHANNEL && UART4_HW_DMA_RX_CHANNEL == GPDMA1_Channel7_BASE_NS || defined UART4_HW_DMA_TX_CHANNEL && UART4_HW_DMA_TX_CHANNEL == GPDMA1_Channel7_BASE_NS \
|| defined UART5_HW_DMA_RX_CHANNEL && UART5_HW_DMA_RX_CHANNEL == GPDMA1_Channel7_BASE_NS || defined UART5_HW_DMA_TX_CHANNEL && UART5_HW_DMA_TX_CHANNEL == GPDMA1_Channel7_BASE_NS \
|| defined UART6_HW_DMA_RX_CHANNEL && UART6_HW_DMA_RX_CHANNEL == GPDMA1_Channel7_BASE_NS || defined UART6_HW_DMA_TX_CHANNEL && UART6_HW_DMA_TX_CHANNEL == GPDMA1_Channel7_BASE_NS
void GPDMA1_Channel7_IRQHandler(void) {
    HAL_DMA_IRQHandler(getDMAHalHandleByDMA(GPDMA1_Channel7));
}
#endif


#if  defined UART1_HW_DMA_RX_CHANNEL &&  UART1_HW_DMA_RX_CHANNEL  == GPDMA2_Channel0_BASE_NS || defined UART1_HW_DMA_TX_CHANNEL && UART1_HW_DMA_TX_CHANNEL == GPDMA2_Channel0_BASE_NS \
    || defined UART2_HW_DMA_RX_CHANNEL && UART2_HW_DMA_RX_CHANNEL == GPDMA2_Channel0_BASE_NS || defined UART2_HW_DMA_TX_CHANNEL && UART2_HW_DMA_TX_CHANNEL == GPDMA2_Channel0_BASE_NS \
    || defined UART3_HW_DMA_RX_CHANNEL && UART3_HW_DMA_RX_CHANNEL == GPDMA2_Channel0_BASE_NS || defined UART3_HW_DMA_TX_CHANNEL && UART3_HW_DMA_TX_CHANNEL == GPDMA2_Channel0_BASE_NS \
    || defined UART4_HW_DMA_RX_CHANNEL && UART4_HW_DMA_RX_CHANNEL == GPDMA2_Channel0_BASE_NS || defined UART4_HW_DMA_TX_CHANNEL && UART4_HW_DMA_TX_CHANNEL == GPDMA2_Channel0_BASE_NS \
    || defined UART5_HW_DMA_RX_CHANNEL && UART5_HW_DMA_RX_CHANNEL == GPDMA2_Channel0_BASE_NS || defined UART5_HW_DMA_TX_CHANNEL && UART5_HW_DMA_TX_CHANNEL == GPDMA2_Channel0_BASE_NS \
    || defined UART6_HW_DMA_RX_CHANNEL && UART6_HW_DMA_RX_CHANNEL == GPDMA2_Channel0_BASE_NS || defined UART6_HW_DMA_TX_CHANNEL && UART6_HW_DMA_TX_CHANNEL == GPDMA2_Channel0_BASE_NS
void GPDMA2_Channel0_IRQHandler(void) {
    HAL_DMA_IRQHandler(getDMAHalHandleByDMA(GPDMA2_Channel0));
}
#endif

#if  defined UART1_HW_DMA_RX_CHANNEL &&  UART1_HW_DMA_RX_CHANNEL  == GPDMA2_Channel1_BASE_NS || defined UART1_HW_DMA_TX_CHANNEL && UART1_HW_DMA_TX_CHANNEL == GPDMA2_Channel1_BASE_NS \
|| defined UART2_HW_DMA_RX_CHANNEL && UART2_HW_DMA_RX_CHANNEL == GPDMA2_Channel1_BASE_NS || defined UART2_HW_DMA_TX_CHANNEL && UART2_HW_DMA_TX_CHANNEL == GPDMA2_Channel1_BASE_NS \
|| defined UART3_HW_DMA_RX_CHANNEL && UART3_HW_DMA_RX_CHANNEL == GPDMA2_Channel1_BASE_NS || defined UART3_HW_DMA_TX_CHANNEL && UART3_HW_DMA_TX_CHANNEL == GPDMA2_Channel1_BASE_NS \
|| defined UART4_HW_DMA_RX_CHANNEL && UART4_HW_DMA_RX_CHANNEL == GPDMA2_Channel1_BASE_NS || defined UART4_HW_DMA_TX_CHANNEL && UART4_HW_DMA_TX_CHANNEL == GPDMA2_Channel1_BASE_NS \
|| defined UART5_HW_DMA_RX_CHANNEL && UART5_HW_DMA_RX_CHANNEL == GPDMA2_Channel1_BASE_NS || defined UART5_HW_DMA_TX_CHANNEL && UART5_HW_DMA_TX_CHANNEL == GPDMA2_Channel1_BASE_NS \
|| defined UART6_HW_DMA_RX_CHANNEL && UART6_HW_DMA_RX_CHANNEL == GPDMA2_Channel1_BASE_NS || defined UART6_HW_DMA_TX_CHANNEL && UART6_HW_DMA_TX_CHANNEL == GPDMA2_Channel1_BASE_NS
void GPDMA2_Channel1_IRQHandler(void) {
    HAL_DMA_IRQHandler(getDMAHalHandleByDMA(GPDMA2_Channel1));
}
#endif


#if  defined UART1_HW_DMA_RX_CHANNEL &&  UART1_HW_DMA_RX_CHANNEL  == GPDMA2_Channel2_BASE_NS || defined UART1_HW_DMA_TX_CHANNEL && UART1_HW_DMA_TX_CHANNEL == GPDMA2_Channel2_BASE_NS \
|| defined UART2_HW_DMA_RX_CHANNEL && UART2_HW_DMA_RX_CHANNEL == GPDMA2_Channel2_BASE_NS || defined UART2_HW_DMA_TX_CHANNEL && UART2_HW_DMA_TX_CHANNEL == GPDMA2_Channel2_BASE_NS \
|| defined UART3_HW_DMA_RX_CHANNEL && UART3_HW_DMA_RX_CHANNEL == GPDMA2_Channel2_BASE_NS || defined UART3_HW_DMA_TX_CHANNEL && UART3_HW_DMA_TX_CHANNEL == GPDMA2_Channel2_BASE_NS \
|| defined UART4_HW_DMA_RX_CHANNEL && UART4_HW_DMA_RX_CHANNEL == GPDMA2_Channel2_BASE_NS || defined UART4_HW_DMA_TX_CHANNEL && UART4_HW_DMA_TX_CHANNEL == GPDMA2_Channel2_BASE_NS \
|| defined UART5_HW_DMA_RX_CHANNEL && UART5_HW_DMA_RX_CHANNEL == GPDMA2_Channel2_BASE_NS || defined UART5_HW_DMA_TX_CHANNEL && UART5_HW_DMA_TX_CHANNEL == GPDMA2_Channel2_BASE_NS \
|| defined UART6_HW_DMA_RX_CHANNEL && UART6_HW_DMA_RX_CHANNEL == GPDMA2_Channel2_BASE_NS || defined UART6_HW_DMA_TX_CHANNEL && UART6_HW_DMA_TX_CHANNEL == GPDMA2_Channel2_BASE_NS
void GPDMA2_Channel2_IRQHandler(void) {
    HAL_DMA_IRQHandler(getDMAHalHandleByDMA(GPDMA2_Channel2));
}
#endif


#if  defined UART1_HW_DMA_RX_CHANNEL &&  UART1_HW_DMA_RX_CHANNEL  == GPDMA2_Channel3_BASE_NS || defined UART1_HW_DMA_TX_CHANNEL && UART1_HW_DMA_TX_CHANNEL == GPDMA2_Channel3_BASE_NS \
|| defined UART2_HW_DMA_RX_CHANNEL && UART2_HW_DMA_RX_CHANNEL == GPDMA2_Channel3_BASE_NS || defined UART2_HW_DMA_TX_CHANNEL && UART2_HW_DMA_TX_CHANNEL == GPDMA2_Channel3_BASE_NS \
|| defined UART3_HW_DMA_RX_CHANNEL && UART3_HW_DMA_RX_CHANNEL == GPDMA2_Channel3_BASE_NS || defined UART3_HW_DMA_TX_CHANNEL && UART3_HW_DMA_TX_CHANNEL == GPDMA2_Channel3_BASE_NS \
|| defined UART4_HW_DMA_RX_CHANNEL && UART4_HW_DMA_RX_CHANNEL == GPDMA2_Channel3_BASE_NS || defined UART4_HW_DMA_TX_CHANNEL && UART4_HW_DMA_TX_CHANNEL == GPDMA2_Channel3_BASE_NS \
|| defined UART5_HW_DMA_RX_CHANNEL && UART5_HW_DMA_RX_CHANNEL == GPDMA2_Channel3_BASE_NS || defined UART5_HW_DMA_TX_CHANNEL && UART5_HW_DMA_TX_CHANNEL == GPDMA2_Channel3_BASE_NS \
|| defined UART6_HW_DMA_RX_CHANNEL && UART6_HW_DMA_RX_CHANNEL == GPDMA2_Channel3_BASE_NS || defined UART6_HW_DMA_TX_CHANNEL && UART6_HW_DMA_TX_CHANNEL == GPDMA2_Channel3_BASE_NS
void GPDMA2_Channel3_IRQHandler(void) {
    HAL_DMA_IRQHandler(getDMAHalHandleByDMA(GPDMA2_Channel3));
}
#endif

#if  defined UART1_HW_DMA_RX_CHANNEL &&  UART1_HW_DMA_RX_CHANNEL  == GPDMA2_Channel4_BASE_NS || defined UART1_HW_DMA_TX_CHANNEL && UART1_HW_DMA_TX_CHANNEL == GPDMA2_Channel4_BASE_NS \
|| defined UART2_HW_DMA_RX_CHANNEL && UART2_HW_DMA_RX_CHANNEL == GPDMA2_Channel4_BASE_NS || defined UART2_HW_DMA_TX_CHANNEL && UART2_HW_DMA_TX_CHANNEL == GPDMA2_Channel4_BASE_NS \
|| defined UART3_HW_DMA_RX_CHANNEL && UART3_HW_DMA_RX_CHANNEL == GPDMA2_Channel4_BASE_NS || defined UART3_HW_DMA_TX_CHANNEL && UART3_HW_DMA_TX_CHANNEL == GPDMA2_Channel4_BASE_NS \
|| defined UART4_HW_DMA_RX_CHANNEL && UART4_HW_DMA_RX_CHANNEL == GPDMA2_Channel4_BASE_NS || defined UART4_HW_DMA_TX_CHANNEL && UART4_HW_DMA_TX_CHANNEL == GPDMA2_Channel4_BASE_NS \
|| defined UART5_HW_DMA_RX_CHANNEL && UART5_HW_DMA_RX_CHANNEL == GPDMA2_Channel4_BASE_NS || defined UART5_HW_DMA_TX_CHANNEL && UART5_HW_DMA_TX_CHANNEL == GPDMA2_Channel4_BASE_NS \
|| defined UART6_HW_DMA_RX_CHANNEL && UART6_HW_DMA_RX_CHANNEL == GPDMA2_Channel4_BASE_NS || defined UART6_HW_DMA_TX_CHANNEL && UART6_HW_DMA_TX_CHANNEL == GPDMA2_Channel4_BASE_NS
void GPDMA2_Channel4_IRQHandler(void) {
    HAL_DMA_IRQHandler(getDMAHalHandleByDMA(GPDMA2_Channel4));
}
#endif

#if  defined UART1_HW_DMA_RX_CHANNEL &&  UART1_HW_DMA_RX_CHANNEL  == GPDMA2_Channel5_BASE_NS || defined UART1_HW_DMA_TX_CHANNEL && UART1_HW_DMA_TX_CHANNEL == GPDMA2_Channel5_BASE_NS \
|| defined UART2_HW_DMA_RX_CHANNEL && UART2_HW_DMA_RX_CHANNEL == GPDMA2_Channel5_BASE_NS || defined UART2_HW_DMA_TX_CHANNEL && UART2_HW_DMA_TX_CHANNEL == GPDMA2_Channel5_BASE_NS \
|| defined UART3_HW_DMA_RX_CHANNEL && UART3_HW_DMA_RX_CHANNEL == GPDMA2_Channel5_BASE_NS || defined UART3_HW_DMA_TX_CHANNEL && UART3_HW_DMA_TX_CHANNEL == GPDMA2_Channel5_BASE_NS \
|| defined UART4_HW_DMA_RX_CHANNEL && UART4_HW_DMA_RX_CHANNEL == GPDMA2_Channel5_BASE_NS || defined UART4_HW_DMA_TX_CHANNEL && UART4_HW_DMA_TX_CHANNEL == GPDMA2_Channel5_BASE_NS \
|| defined UART5_HW_DMA_RX_CHANNEL && UART5_HW_DMA_RX_CHANNEL == GPDMA2_Channel5_BASE_NS || defined UART5_HW_DMA_TX_CHANNEL && UART5_HW_DMA_TX_CHANNEL == GPDMA2_Channel5_BASE_NS \
|| defined UART6_HW_DMA_RX_CHANNEL && UART6_HW_DMA_RX_CHANNEL == GPDMA2_Channel5_BASE_NS || defined UART6_HW_DMA_TX_CHANNEL && UART6_HW_DMA_TX_CHANNEL == GPDMA2_Channel5_BASE_NS
void GPDMA2_Channel5_IRQHandler(void) {
    HAL_DMA_IRQHandler(getDMAHalHandleByDMA(GPDMA2_Channel5));
}
#endif


#if  defined UART1_HW_DMA_RX_CHANNEL &&  UART1_HW_DMA_RX_CHANNEL  == GPDMA2_Channel6_BASE_NS || defined UART1_HW_DMA_TX_CHANNEL && UART1_HW_DMA_TX_CHANNEL == GPDMA2_Channel6_BASE_NS \
|| defined UART2_HW_DMA_RX_CHANNEL && UART2_HW_DMA_RX_CHANNEL == GPDMA2_Channel6_BASE_NS || defined UART2_HW_DMA_TX_CHANNEL && UART2_HW_DMA_TX_CHANNEL == GPDMA2_Channel6_BASE_NS \
|| defined UART3_HW_DMA_RX_CHANNEL && UART3_HW_DMA_RX_CHANNEL == GPDMA2_Channel6_BASE_NS || defined UART3_HW_DMA_TX_CHANNEL && UART3_HW_DMA_TX_CHANNEL == GPDMA2_Channel6_BASE_NS \
|| defined UART4_HW_DMA_RX_CHANNEL && UART4_HW_DMA_RX_CHANNEL == GPDMA2_Channel6_BASE_NS || defined UART4_HW_DMA_TX_CHANNEL && UART4_HW_DMA_TX_CHANNEL == GPDMA2_Channel6_BASE_NS \
|| defined UART5_HW_DMA_RX_CHANNEL && UART5_HW_DMA_RX_CHANNEL == GPDMA2_Channel6_BASE_NS || defined UART5_HW_DMA_TX_CHANNEL && UART5_HW_DMA_TX_CHANNEL == GPDMA2_Channel6_BASE_NS \
|| defined UART6_HW_DMA_RX_CHANNEL && UART6_HW_DMA_RX_CHANNEL == GPDMA2_Channel6_BASE_NS || defined UART6_HW_DMA_TX_CHANNEL && UART6_HW_DMA_TX_CHANNEL == GPDMA2_Channel6_BASE_NS
void GPDMA2_Channel6_IRQHandler(void) {
    HAL_DMA_IRQHandler(getDMAHalHandleByDMA(GPDMA2_Channel6));
}
#endif

#if  defined UART1_HW_DMA_RX_CHANNEL &&  UART1_HW_DMA_RX_CHANNEL  == GPDMA2_Channel7_BASE_NS || defined UART1_HW_DMA_TX_CHANNEL && UART1_HW_DMA_TX_CHANNEL == GPDMA2_Channel7_BASE_NS \
|| defined UART2_HW_DMA_RX_CHANNEL && UART2_HW_DMA_RX_CHANNEL == GPDMA2_Channel7_BASE_NS || defined UART2_HW_DMA_TX_CHANNEL && UART2_HW_DMA_TX_CHANNEL == GPDMA2_Channel7_BASE_NS \
|| defined UART3_HW_DMA_RX_CHANNEL && UART3_HW_DMA_RX_CHANNEL == GPDMA2_Channel7_BASE_NS || defined UART3_HW_DMA_TX_CHANNEL && UART3_HW_DMA_TX_CHANNEL == GPDMA2_Channel7_BASE_NS \
|| defined UART4_HW_DMA_RX_CHANNEL && UART4_HW_DMA_RX_CHANNEL == GPDMA2_Channel7_BASE_NS || defined UART4_HW_DMA_TX_CHANNEL && UART4_HW_DMA_TX_CHANNEL == GPDMA2_Channel7_BASE_NS \
|| defined UART5_HW_DMA_RX_CHANNEL && UART5_HW_DMA_RX_CHANNEL == GPDMA2_Channel7_BASE_NS || defined UART5_HW_DMA_TX_CHANNEL && UART5_HW_DMA_TX_CHANNEL == GPDMA2_Channel7_BASE_NS \
|| defined UART6_HW_DMA_RX_CHANNEL && UART6_HW_DMA_RX_CHANNEL == GPDMA2_Channel7_BASE_NS || defined UART6_HW_DMA_TX_CHANNEL && UART6_HW_DMA_TX_CHANNEL == GPDMA2_Channel7_BASE_NS
void GPDMA2_Channel7_IRQHandler(void) {
    HAL_DMA_IRQHandler(getDMAHalHandleByDMA(GPDMA2_Channel7));
}
#endif
